version: '3.8'
services:
  php-apache-environement:
    container_name: boggle-web-server
    build:
      context: ./public
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./public:/var/www/html/
    ports: 
      - 8000:80
  db:
    container_name: db-by-boggle
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boogle
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - 9906:3306
  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
